development:
  adapter: redis
  url: "redis://127.0.0.1:6379/0"

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:32ecc4a3567a4f57b64acdb8fa984587@sculpin.redistogo.com:11142/
