Tag.create([
  {name:"Mineral Products"},
  {name:"Wood Products"},
  {name:"Metals"},
  {name:"Stone and Glass"},
  {name:"Animal and Vegetable Bi-Products"},
  {name:"Paper Goods"},
  {name:"Vegetable Products"},
  {name:"Animal Products"},
  {name:"Foodstuffs"},
  {name:"Weapons"},
  {name:"Footwear and Headwear"},
  {name:"Animal Hides"},
  {name:"Textiles"},
  {name:"Transportation"},
  {name:"Machines"},
  {name:"Arts and Antiques"},
  {name:"Precious Metals"},
  {name:"Chemical Products"},
  {name:"Instruments"},
  {name:"Plastics and Rubbers"},
  {name:"Miscellaneous"}
])